name: Release + Publish to AUR

on:
  push:
    tags:
      - "v*"        # Trigger on new tags
    paths:
      - PKGBUILD

env:
  PKG_NAME: ai-pkg-bin

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine installer
      
      - name: Update pyproject.toml version from tag
        run: |
          TAG=${{ github.ref_name }}
          VERSION=${TAG#v}
          sed -i "s/^version = \".*\"/version = \"$VERSION\"/" pyproject.toml
          echo "Updated pyproject.toml to version $VERSION"
      
      - name: Build wheel
        run: python -m build
      
      - name: Normalize wheel name
        run: |
          FILE=$(ls dist/*.whl | head -n 1)
          VERSION=${{ github.ref_name }}
          VERSION=${VERSION#v}
          echo "Wheel file before rename: $FILE"
          # Only rename if filename does not already contain correct version
          BASENAME=$(basename "$FILE")
          if [[ "$BASENAME" != *"$VERSION"* ]]; then
            BASENAME=$(echo "$BASENAME" | sed "s/[0-9]\+\.[0-9]\+\.[0-9]\+/$VERSION/")
            NEW_NAME="dist/$BASENAME"
            mv "$FILE" "$NEW_NAME"
            echo "Renamed wheel to $NEW_NAME"
          else
            NEW_NAME="$FILE"
            echo "Wheel already has correct version: $NEW_NAME"
          fi

      - name: List wheel files
        run: ls -l dist/

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update PKGBUILD version and SHA256
        run: |
          TAG=${{ github.ref_name }}
          VERSION=${TAG#v}
          echo "Updating PKGBUILD to version $VERSION"
          # Update pkgver
          sed -i "s/^pkgver=.*/pkgver=$VERSION/" PKGBUILD
          # Keep your URL as-is (tag URL)
          sed -i "s|source=(\".*\")|source=(\"https://github.com/rohankrsingh/ai-pkg/releases/tag/v$VERSION/ai-pkg-$VERSION.whl\")|" PKGBUILD
          # Compute SHA256 from wheel file
          FILE=$(ls dist/*.whl | head -n 1)
          SHA256=$(sha256sum "$FILE" | cut -d ' ' -f1)
          sed -i "s|sha256sums=('REPLACE_ME')|sha256sums=('$SHA256')|" PKGBUILD
          echo "PKGBUILD updated"

  aur-publish:
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Publish to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v2.7.0
        with:
          pkgname: ai-pkg-bin
          pkgbuild: ./PKGBUILD
          commit_username: "rohankrsingh"
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_KEY }}
          commit_message: "Update to ${{ github.ref_name }}"
          ssh_keyscan_types: rsa,ecdsa,ed25519
