name: Release + Publish to AUR

on:
  push:
    tags:
      - "v*"        # Trigger on new tags
    paths:
      - PKGBUILD

env:
  PKG_NAME: ai-pkg-bin

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine installer

      - name: Build wheel
        run: python -m build

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute SHA256 of wheel and update PKGBUILD
        env:
          TAG: ${{ github.ref_name }}
        run: |
          VERSION=${TAG#v}
          FILE=dist/ai-pkg-${VERSION}-py3-none-any.whl
          if [ ! -f "$FILE" ]; then
            echo "ERROR: Wheel file not found: $FILE"
            exit 1
          fi
          SHA256=$(sha256sum "$FILE" | cut -d ' ' -f1)
          echo "Computed SHA256: $SHA256"
          sed -i "s|REPLACE_ME|$SHA256|" PKGBUILD

  aur-publish:
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Publish to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v2.7.0
        with:
          pkgname: ai-pkg-bin
          pkgbuild: ./PKGBUILD
          commit_username: "github-actions"
          commit_email: "actions@github.com"
          ssh_private_key: ${{ secrets.AUR_SSH_KEY }}
          commit_message: "Update to ${{ github.ref_name }}"
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
